/**
  ******************************************************************************
  * @file    apie_ml.h
  * @brief   Embedded ML inference (online Naive Bayes + logistic decision).
  *
  * Model selection rationale: the classification targets here ("will query X
  * be answered?", "is this unknown message power-correlated?") are small and
  * heavily feature-conditional, so a compact Naive Bayes classifier trained
  * ONLINE on the MCU is more appropriate than a heavy neural net.  A tiny
  * logistic head is retained for the concrete useful/not-useful probability.
  *
  * There are NO random weights.  Every parameter is either (a) learned online
  * from observed outcomes with Laplace smoothing, or (b) a documented seed
  * prior generated by the host training pipeline (tools/train_apie.py).
  ******************************************************************************
  */
#ifndef APIE_ML_H
#define APIE_ML_H

#ifdef __cplusplus
extern "C" {
#endif

#include "apie.h"
#include "apie_analyzer.h"

/* Feature bins used by the online Naive Bayes classifier. */
typedef enum
{
  APIE_NB_FEAT_QUERY   = 0,  /* query id 0..8                 */
  APIE_NB_FEAT_ATTEMPT = 1,  /* 0=first,1=retry,2=many        */
  APIE_NB_FEAT_HASPPS  = 2,  /* source offers PPS             */
  APIE_NB_FEAT_HARD    = 3,  /* source hard identity known    */
  APIE_NB_FEAT_COUNT   = 4
} APIE_NbFeature_t;

#define APIE_NB_QUERY_BINS 9U

/* Model metadata + parameters for the classification head. */
typedef struct
{
  APIE_ModelMeta_t meta;
  /* class "useful" prior count and per-class likelihoods for each feature bin.
     Structured as count[class][feature][bin-of-feature].  Classes: 0=not useful,
     1=useful.  Laplace smoothing is applied at inference time. */
  uint32_t nclass[2];
  uint32_t ncount[2][APIE_NB_FEAT_COUNT][8];
  /* logistic head: 4 weights + bias for useful probability. */
  float logit_w[APIE_FEATURE_COUNT];
  float logit_b;
} APIE_MlModel_t;

void APIE_Ml_Init(void);
void APIE_Ml_Reset(void);
const APIE_MlModel_t *APIE_Ml_GetModel(void);
/* Online update: after a transaction outcome known. query 0..8, success 0/1. */
void APIE_Ml_Observe(uint8_t query, uint8_t attempt, uint8_t has_pps, uint8_t hard_known,
                     uint8_t success);
/* Infer P(class=useful | full feature vector). */
float APIE_Ml_PredictUseful(const APIE_FeatureVec_t *fv, uint8_t query);
/* Infer class (0/1) given the feature vector. */
uint8_t APIE_Ml_Classify(const APIE_FeatureVec_t *fv, uint8_t query);
/* Validate the model CRC and metadata. */
uint8_t APIE_Ml_Validate(void);
/* Export raw model bytes into a caller buffer; returns length. */
uint16_t APIE_Ml_Export(uint8_t *out, uint16_t outsz);
/* Import a packaged model (host-generated); returns 1 on success. */
uint8_t APIE_Ml_Import(const uint8_t *in, uint16_t len);

/* ---------------------------------------------------------------------------
 *  Additional model types (section E):
 *   - a compact decision-tree classifier for "is query Q likely supported",
 *     defined by explicit structural rules (interpretable, not random);
 *   - an online Gaussian anomaly detector over transaction latency.
 * Both are deterministic, bounded, and safety-subordinated (ML never gates
 * electrical action without the deterministic safety checks in apie_plan.c).
 * ------------------------------------------------------------------------- */

/* Decision-tree inference.  Returns 0/1 ("not useful"/"useful") for query id
   0..8 given the current feature vector.  The tree is a fixed, documented set
   of evidence-justified thresholds (has-PPS, hard-identity-known, retry
   count, advertisement latency) — not learned random weights. */
uint8_t APIE_Tree_ClassifyUseful(const APIE_FeatureVec_t *fv, uint8_t query);

/* Anomaly detection.  Maintains an online mean/std of a scalar (e.g.
   transaction latency) and flags a value that deviates by more than k sigma.
   The detector is bounded (Welford) and never affects safety decisions. */
void APIE_Ml_Anomaly_Observe(float x);
uint8_t APIE_Ml_Anomaly_Flag(float x, float k_sigma);   /* 1 = anomalous */
float APIE_Ml_Anomaly_Mean(void);
float APIE_Ml_Anomaly_Std(void);
uint32_t APIE_Ml_Anomaly_Count(void);
uint8_t APIE_Ml_Anomaly_Trained(void);   /* 1 once enough samples observed */

#ifdef __cplusplus
}
#endif

#endif /* APIE_ML_H */
