/* Generated by tools/train_apie.py - do not edit by hand. */
#ifndef APIE_MODEL_SEED_H
#define APIE_MODEL_SEED_H

#define APIE_MODEL_SEED_ACCURACY 1.0000f
#define APIE_MODEL_SEED_NPROFILES 0

static const uint32_t api_seed_nclass[2] = { 30, 34 };
static const uint32_t api_seed_ncount[2][4][8] =
{
  { /* class 0 */
    { 0, 0, 10, 5, 0, 0, 0, 15 },
    { 30, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 30, 0, 0, 0, 0, 0, 0 },
    { 0, 30, 0, 0, 0, 0, 0, 0 },
  },
  { /* class 1 */
    { 11, 8, 0, 0, 0, 7, 8, 0 },
    { 34, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 34, 0, 0, 0, 0, 0, 0 },
    { 0, 34, 0, 0, 0, 0, 0, 0 },
  },
};
static const float api_seed_useful_rate = 0.5312f;
static const uint32_t api_seed_crc = 0x60BDE64Bu;

#endif /* APIE_MODEL_SEED_H */
